name: Build and generate docs

on:
  push:
    branches-ignore:
      - docs
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [1.8, 11, 17]  # We're building on all Java LTS versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-package: jdk
          java-version: ${{ matrix.java }}

      - name: Make Gradle executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x gradlew

      - name: Build using Gradle
        run: ./gradlew build

      - name: Extract branch name
        id: extract_branch
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '1.8' }}  # Only deploy docs once
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Deploy documentation
        if: ${{ github.event_name == 'push' && runner.os == 'Linux' && matrix.java == '1.8' }}  # Only deploy docs once
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/html
          publish_branch: docs-${{ steps.extract_branch.outputs.branch }}
          force_orphan: true
